import type { Question, Unit, Vocab } from "@/lib/workbook";
import { EXTRA_VOCAB, PRACTICE } from "./book-practice.ts";

export const BOOK_BANK = "efs-17-v4";

function v(id: string, word: string, sentence: string): Vocab {
  return { id, word, sentence };
}

function q(id: string, prompt: string, answer: string): Question {
  return { id, prompt, answer };
}

export function bookUnits(): Unit[] {
  const units: Unit[] = [
    {
      id: "u01",
      label: "Unit 1: Management",
      vocab: [
        v("u01v1", "management", "The process used to accomplish organizational goals through planning, organizing, leading, and controlling people and other organizational resources."),
        v("u01v2", "manager", "An individual who is in charge of a certain group of tasks, or a certain area or department of a business."),
        v("u01v3", "Chief Executive Officer | CEO", "The most senior manager responsible for the overall performance and success of a company."),
        v("u01v4", "planning", "A management function that includes anticipating trends and determining the best strategies and tactics to achieve organizational goals and objectives."),
        v("u01v5", "planning", "involves setting aims or targets for the future of the organization to give it a sense of direction or purpose. Managers must also plan for the resources (physical, human, and financial) that will be needed to achieve these strategies."),
        v("u01v6", "organizing", "A management function that includes designing the structure of the organization and creating conditions and systems in which everyone and everything work together to achieve the organization's goals and objectives."),
        v("u01v7", "organizing", "A manager cannot do everything alone; tasks must be delegated to others. Managers must ensure that subordinates have the necessary resources to perform their tasks successfully. An organizational chart is used to show authority and ensure specialization, preventing two people from performing overlapping tasks."),
        v("u01v8", "leading", "Creating a vision for the organization and guiding, training, coaching, and motivating others to work effectively to achieve the organization's goals and objectives."),
        v("u01v9", "controlling", "A management function that involves establishing clear standards to determine whether or not an organization is progressing toward its goals and objectives, rewarding people for doing a good job, and taking corrective action if they are not."),
        v("u01v10", "controlling", "This is a never-ending task where managers must measure and evaluate the performance of all individuals and groups against the original plans. If targets are not met, the manager must find the causes and take corrective action (such as providing staff training)."),
        v("u01v11", "coordinating", "means \"bringing together\" different individuals and departments (such as Marketing and Production) to work towards the plans. Without coordination, departments might work in isolation, leading to a lack of communication and uncoordinated efforts."),
        v("u01v12", "commanding", "is more concerned with guiding, leading, and supervising people than just telling them what to do. Managers must ensure that supervisors and workers are keeping to targets and deadlines by providing instructions and guidance."),
        v("u01v13", "entrepreneurs", "are alert to undiscovered profit opportunities. They perceive opportunities to commercialize new technologies and products that serve the market better. They are highly unconventional, innovative people who risk their own or other people's capital."),
      ],
      questions: [
        q("u01q1", "Managers are awarded formal, tangible power and authority by virtue of what?", "their position within the organization"),
        q("u01q2", "What is a leader's influence based on?", "their personal qualities"),
        q("u01q3", "A leader's influence is awarded on what kind of basis?", "a temporary basis | temporary"),
        q("u01q4", "What do managers spend much of their time doing?", "upholding the status quo of the organization | upholding the status quo"),
        q("u01q5", "Why do leaders often challenge the status quo?", "to bring innovation to organizations | to bring innovation"),
        q("u01q6", "What are managers concerned with?", "the bottom line"),
        q("u01q7", "What are leaders looking at?", "the horizon"),
        q("u01q8", "Which resources must managers plan for?", "physical, human, and financial | physical, human and financial"),
        q("u01q9", "What is used to show authority and ensure specialization?", "an organizational chart | organizational chart"),
        q("u01q10", "What does coordinating mean?", "bringing together"),
        q("u01q11", "Which two departments are named as an example that must be coordinated?", "Marketing and Production"),
        q("u01q12", "Commanding is more concerned with what, rather than just telling people what to do?", "guiding, leading, and supervising people | guiding, leading and supervising people"),
        q("u01q13", "If targets are not met, what must the manager do?", "find the causes and take corrective action"),
        q("u01q14", "What are entrepreneurs alert to?", "undiscovered profit opportunities"),
        q("u01q15", "Who is needed to run a business in the long term?", "a manager | manager"),
      ],
    },
    {
      id: "u02",
      label: "Unit 2: Work and Motivation",
      vocab: [
        v("u02v1", "motivation", "factors that influence the behavior of workers towards achieving business goals. It can be increased by monetary rewards, non-monetary rewards, and introducing ways to give job satisfaction."),
        v("u02v2", "job satisfaction", "The enjoyment a worker gets from feeling that they have done a good job."),
        v("u02v3", "job rotation", "swapping workers round and only doing a specific task for a limited time before swapping round again."),
        v("u02v4", "job enlargement", "extra tasks are added to the job to make it more interesting."),
        v("u02v5", "job enrichment", "adding tasks that require more skill and/or responsibility."),
        v("u02v6", "Theory X", "The average person does not like work. Workers must be constantly supervised so they will work. Motivation is from external factors, for example pay schemes where the workers are paid more for increased output."),
        v("u02v7", "Theory Y", "The average person is motivated by internal factors. To motivate workers, you need to find ways to help workers take an interest in their work, for example give rewards and incentives."),
        v("u02v8", "Maslow's hierarchy of needs", "A theory of motivation which states that five categories of human needs dictate an individual's behavior. Those needs are physiological needs, safety needs, love and belonging needs, esteem needs, and self-actualization needs."),
        v("u02v9", "hygiene factors", "The factors that must be present in the workplace to prevent job dissatisfaction."),
        v("u02v10", "motivators", "The needs that allow a human being to grow psychologically. Herzberg called these motivational needs."),
      ],
      questions: [
        q("u02q1", "What three things can increase motivation?", "monetary rewards, non-monetary rewards, and job satisfaction | monetary rewards, non-monetary rewards, and introducing ways to give job satisfaction"),
        q("u02q2", "What are the three ways to motivate workers to be more committed to their jobs?", "job rotation, job enlargement, and job enrichment"),
        q("u02q3", "In Theory X, where does motivation come from?", "external factors"),
        q("u02q4", "In Theory Y, the average person is motivated by what?", "internal factors"),
        q("u02q5", "Name Maslow's five categories of needs.", "physiological needs, safety needs, love and belonging needs, esteem needs, and self-actualization needs"),
        q("u02q6", "What must be present in the workplace to prevent job dissatisfaction?", "hygiene factors"),
        q("u02q7", "What did Herzberg call the needs that let a person grow psychologically?", "motivational needs | motivators"),
      ],
    },
    {
      id: "u03",
      label: "Unit 3: Company Structure",
      vocab: [
        v("u03v1", "organizational structure", "The levels of management and division of responsibilities within an organization."),
        v("u03v2", "hierarchy", "The levels of management in any organization, from the highest to the lowest."),
        v("u03v3", "chain of command", "The structure in an organization which allows instructions to be passed down from senior management to lower levels of management."),
        v("u03v4", "span of control", "The number of subordinates working directly under a manager."),
        v("u03v5", "directors", "Senior managers who lead a particular department or division of a business."),
        v("u03v6", "line managers", "People who have responsibility for people below them in the hierarchy of an organization."),
        v("u03v7", "supervisors", "Junior managers who have direct control over the employees below them in the organizational structure."),
        v("u03v8", "staff managers", "Specialists who provide support, information and assistance to line managers."),
        v("u03v9", "delegation", "Giving a subordinate the authority to perform a particular task."),
        v("u03v10", "decentralization", "Taking decisions away from the centre of an organization, away from the Head Office."),
        v("u03v11", "outsourcing", "transferring some of the company's internal functions or operations or jobs to outside suppliers, rather than performing them in-house."),
      ],
      questions: [
        q("u03q1", "What is passed down from senior management to lower levels of management?", "instructions"),
        q("u03q2", "What does span of control count?", "the number of subordinates working directly under a manager"),
        q("u03q3", "Who provides support, information and assistance to line managers?", "staff managers"),
        q("u03q4", "What is given to a subordinate so they can perform a particular task?", "authority | the authority"),
        q("u03q5", "Decentralization takes decisions away from where?", "the Head Office | the centre of an organization"),
        q("u03q6", "What is the opposite of performing work in-house, when jobs go to outside suppliers?", "outsourcing"),
      ],
    },
    {
      id: "u04",
      label: "Unit 4: Managing across Cultures",
      vocab: [
        v("u04v1", "glocalization", "a combination of the words globalization and localization. The term is used to describe a product or service that is developed and distributed globally but is also adjusted to accommodate the user or consumer in a local market."),
        v("u04v2", "culture", "the complex system of values, traits, morals, and customs shared by a society."),
        v("u04v3", "context", "the stimuli, environment, or ambience surrounding an event."),
        v("u04v4", "the Lewis Model", "divides humans into 3 clear categories, based not on nationality or religion but on behaviour: Linear-active, Multi-active and Reactive."),
        v("u04v5", "high-context culture", "a culture in which the rules of communication are primarily transmitted through contextual elements, including body language, the status of an individual, and the tone of voice. Rules are usually not explicitly written or stated."),
        v("u04v6", "low-context culture", "a culture whereby most communications take place through verbal language and rules are directly written out or stated for all to view."),
      ],
      questions: [
        q("u04q1", "Glocalization combines which two words?", "globalization and localization"),
        q("u04q2", "A glocal product is developed globally but adjusted for whom?", "the user or consumer in a local market | a local market"),
        q("u04q3", "The Lewis Model is based on behaviour, not on what?", "nationality or religion"),
        q("u04q4", "Name the three Lewis categories.", "Linear-active, Multi-active and Reactive"),
        q("u04q5", "In a high-context culture, are the rules usually written down?", "no | No"),
        q("u04q6", "In a low-context culture, most communication takes place through what?", "verbal language"),
      ],
    },
    {
      id: "u05",
      label: "Unit 5: Recruitment",
      vocab: [
        v("u05v1", "recruitment", "the process from identifying that the business needs to employ someone up to the point at which applications have arrived at the business."),
        v("u05v2", "employee selection", "the process of evaluating candidates for a specific job and selecting an individual for employment based on the needs of the organisation."),
        v("u05v3", "job analysis", "identifies and records the responsibilities and tasks relating to a job."),
        v("u05v4", "job description", "outlines the responsibilities and duties to be carried out by someone employed to do a specific job."),
        v("u05v5", "job specification", "a document which outlines the requirements, qualifications, expertise, physical characteristics, and so on, for a specified job."),
        v("u05v6", "internal recruitment", "when a vacancy is filled by someone who is an existing employee of the business."),
        v("u05v7", "external recruitment", "when a vacancy is filled by someone who is not an existing employee and will be new to the business."),
        v("u05v8", "induction training", "an introduction given to a new employee, explaining the business's activities, customs and procedures and introducing them to their fellow workers."),
        v("u05v9", "on-the-job training", "occurs by watching a more experienced worker doing the job."),
        v("u05v10", "off-the-job training", "involves being trained away from the workplace, usually by specialist trainers."),
      ],
      questions: [
        q("u05q1", "Recruitment ends at the point when what has arrived at the business?", "applications"),
        q("u05q2", "Which document outlines responsibilities and duties of a specific job?", "a job description | job description"),
        q("u05q3", "Which document outlines requirements, qualifications and expertise for a job?", "a job specification | job specification"),
        q("u05q4", "Who fills a vacancy in internal recruitment?", "an existing employee"),
        q("u05q5", "Who fills a vacancy in external recruitment?", "someone who is not an existing employee | someone new to the business"),
        q("u05q6", "On-the-job training happens by watching whom?", "a more experienced worker"),
        q("u05q7", "Where does off-the-job training take place?", "away from the workplace"),
      ],
    },
    {
      id: "u06",
      label: "Unit 6: Classification of Businesses",
      vocab: [
        v("u06v1", "primary sector", "extracts and uses the natural resources of Earth to produce raw materials used by other businesses."),
        v("u06v2", "secondary sector", "manufactures goods using the raw materials provided by the primary sector."),
        v("u06v3", "tertiary sector", "provides services to consumers and the other sectors of industry."),
        v("u06v4", "mixed economy", "has both a private sector and a public (state) sector."),
        v("u06v5", "public sector", "the sector of the economy in which organisations are owned and controlled by the state (government)."),
        v("u06v6", "private sector", "The sector of the economy in which organisations are owned and controlled by individuals."),
        v("u06v7", "privatisation", "The sale of state-owned assets such as public corporations to the private sector."),
        v("u06v8", "sole trader", "a business owned and operated by one person."),
        v("u06v9", "limited liability", "the liability of shareholders in a company is limited to only the amount they invested."),
        v("u06v10", "unlimited liability", "the owners of a business can be held responsible for the debts of the business they own. Their liability is not limited to the investment they made in the business."),
        v("u06v11", "partnership", "a form of business in which two or more people agree to jointly own a business."),
        v("u06v12", "shareholders", "the owners of a limited company. They buy shares which represent part-ownership of the company."),
        v("u06v13", "private limited company", "businesses owned by shareholders but they cannot sell shares to the public."),
        v("u06v14", "public limited company", "businesses owned by shareholders but they can sell shares to the public and their shares are tradeable on the Stock Exchange."),
      ],
      questions: [
        q("u06q1", "Which sector extracts natural resources to produce raw materials?", "the primary sector | primary sector"),
        q("u06q2", "Which sector manufactures goods?", "the secondary sector | secondary sector"),
        q("u06q3", "Which sector provides services?", "the tertiary sector | tertiary sector"),
        q("u06q4", "Who owns and controls public-sector organisations?", "the state | the government"),
        q("u06q5", "Privatisation is the sale of state-owned assets to whom?", "the private sector"),
        q("u06q6", "How many people own a sole trader?", "one | one person"),
        q("u06q7", "Limited liability is limited to what?", "only the amount they invested | the amount they invested"),
        q("u06q8", "How many people jointly own a partnership?", "two or more"),
        q("u06q9", "Can a private limited company sell shares to the public?", "no | No"),
        q("u06q10", "Where are the shares of a public limited company tradeable?", "on the Stock Exchange | the Stock Exchange"),
      ],
    },
    {
      id: "u07",
      label: "Unit 7: Production",
      vocab: [
        v("u07v1", "production", "the process of converting inputs such as land, labour and capital into saleable goods, for example shoes and cell phones."),
        v("u07v2", "inventories", "the stock of raw materials, work-in-progress and finished goods held by a business."),
        v("u07v3", "lean production", "the production of goods and services with the minimum waste of resources."),
        v("u07v4", "job production", "the production of items one at a time."),
        v("u07v5", "batch production", "the production of goods in batches. Each batch passes through one stage of production before moving onto the next stage."),
        v("u07v6", "flow production", "the production of very large quantities of identical goods using a continuously moving process."),
        v("u07v7", "just-in-time | JIT", "a production method that involves reducing or virtually eliminating the need to hold inventories of raw materials or unsold inventories of the finished product."),
      ],
      questions: [
        q("u07q1", "Production converts inputs such as land, labour and capital into what?", "saleable goods"),
        q("u07q2", "Inventories include raw materials, work-in-progress and what else?", "finished goods"),
        q("u07q3", "Lean production keeps waste of resources to what?", "a minimum | the minimum"),
        q("u07q4", "Job production makes items how?", "one at a time"),
        q("u07q5", "Flow production uses what kind of process?", "a continuously moving process"),
        q("u07q6", "Just-in-time tries to eliminate the need to hold what?", "inventories"),
      ],
    },
    {
      id: "u08",
      label: "Unit 8: Logistics",
      vocab: [
        v("u08v1", "logistics", "the business activity that involves planning, implementing, and controlling the physical flow of materials, final goods, and related information from points of origin to points of consumption to meet customer requirements at a profit."),
        v("u08v2", "inbound logistics", "the area of logistics that involves bringing raw materials, packaging, other goods and services, and information from suppliers to producers."),
        v("u08v3", "materials handling", "the movement of goods within a warehouse, from warehouses to the factory floor, and from the factory floor to various workstations."),
        v("u08v4", "outbound logistics", "the area of logistics that involves managing the flow of finished products and information to business buyers and ultimate consumers."),
        v("u08v5", "reverse logistics", "the area of logistics that involves bringing goods back to the manufacturer because of defects or for recycling."),
      ],
      questions: [
        q("u08q1", "Logistics moves materials and goods from points of origin to where?", "points of consumption"),
        q("u08q2", "Inbound logistics brings raw materials from suppliers to whom?", "producers"),
        q("u08q3", "Materials handling is the movement of goods inside what?", "a warehouse | the warehouse"),
        q("u08q4", "Outbound logistics manages the flow of what?", "finished products | finished products and information"),
        q("u08q5", "Why does reverse logistics bring goods back to the manufacturer?", "because of defects or for recycling"),
      ],
    },
    {
      id: "u09",
      label: "Unit 9: Quality",
      vocab: [
        v("u09v1", "quality", "to produce a good or a service which meets customer expectations."),
        v("u09v2", "quality control", "the checking for quality at the end of the production process, whether it is the production of a product or service."),
        v("u09v3", "quality assurance", "the checking for quality standards throughout the production process, whether it is the production of a product or service."),
        v("u09v4", "Total Quality Management | TQM", "the continuous improvement of products and processes by focusing on quality at each stage of production."),
      ],
      questions: [
        q("u09q1", "Quality means meeting whose expectations?", "customer expectations | the customer's expectations"),
        q("u09q2", "Quality control checks quality at which point?", "at the end of the production process | the end of the production process"),
        q("u09q3", "Quality assurance checks quality standards when?", "throughout the production process"),
        q("u09q4", "Total Quality Management focuses on quality at which stage?", "each stage of production | at each stage of production"),
      ],
    },
    {
      id: "u10",
      label: "Unit 10: Marketing",
      vocab: [
        v("u10v1", "market", "the set of all actual and potential buyers of a good or service."),
        v("u10v2", "market leader", "the company with the largest market share."),
        v("u10v3", "market nicher", "a small company that concentrates on one or more particular niches or small market segments."),
        v("u10v4", "market research | marketing research", "the collection, analysis and reporting of data relevant to a specific marketing situation."),
        v("u10v5", "market segment", "part of a market; a group of customers with specific needs, defined in terms of geography, age, sex, income, occupation, life-style, and so on."),
        v("u10v6", "market segmentation", "the act of dividing a market into distinct groups of buyers who have different requirements or buying habits."),
        v("u10v7", "market share", "the sales of a company, brand or product expressed as a percentage of total sales in a market."),
        v("u10v8", "marketing", "the process of identifying and satisfying consumers' needs and desires."),
        v("u10v9", "marketing channel", "the set of intermediaries a company uses to get its goods to their end users."),
        v("u10v10", "marketing mix", "the set of all the various elements in a marketing programme, and the way a company integrates them."),
        v("u10v11", "marketing strategy", "a plan or principle designed to achieve marketing objectives."),
        v("u10v12", "product life cycle", "the standard pattern of sales of a product over the period that it is marketed."),
      ],
      questions: [
        q("u10q1", "The market leader is the company with the largest what?", "market share"),
        q("u10q2", "A market nicher concentrates on what?", "niches | small market segments | particular niches"),
        q("u10q3", "Market share is expressed as a percentage of what?", "total sales"),
        q("u10q4", "Marketing identifies and satisfies whose needs and desires?", "consumers' | consumers"),
        q("u10q5", "A marketing channel is the set of intermediaries used to reach whom?", "end users"),
        q("u10q6", "A marketing strategy is designed to achieve what?", "marketing objectives"),
      ],
    },
    {
      id: "u11",
      label: "Unit 11: Advertising",
      vocab: [
        v("u11v1", "advertorial", "A paid-for advertisement which includes editorial content, normally identified in a print magazine with the word Advertisement so it is distinct from genuine editorial content."),
        v("u11v2", "advertising agency", "The organization that takes care of advertising for clients."),
        v("u11v3", "advertising campaign", "A time-limited set of ads. Campaigns may run across different media, and for one month or ten years, but they are the execution of a central idea."),
        v("u11v4", "demographics", "Describing an audience by age, gender, ethnicity, or location — the facts about them."),
        v("u11v5", "focus groups", "Small, select groups representing a target audience who are paid to answer questions at the behest of a market research organization."),
        v("u11v6", "product placement", "The practice of paying for a branded product to be used by a character in a movie, for example James Bond driving a BMW Z3."),
        v("u11v7", "product positioning", "Establishing the market niche of a product — which may not be as the brand leader — and advertising to the appropriate segment of the audience."),
        v("u11v8", "unique selling proposition | USP | unique selling point", "a highlighted benefit of a product which makes it stand out from all rival brands."),
      ],
      questions: [
        q("u11q1", "An advertorial is paid for and also includes what kind of content?", "editorial content"),
        q("u11q2", "Who takes care of advertising for clients?", "an advertising agency | advertising agency"),
        q("u11q3", "Demographics describe an audience by age, gender, ethnicity, or what?", "location"),
        q("u11q4", "Focus groups represent whom?", "a target audience"),
        q("u11q5", "Product placement pays for a branded product to be used where?", "in a movie | by a character in a movie"),
        q("u11q6", "A USP is a highlighted benefit that makes a product stand out from what?", "all rival brands | rival brands"),
      ],
    },
    {
      id: "u12",
      label: "Unit 12: Banking",
      vocab: [
        v("u12v1", "deposit", "to place money in a bank; or money placed in a bank."),
        v("u12v2", "liquidity", "available cash, and how easily other assets can be turned into cash."),
        v("u12v3", "collateral", "anything that acts as a security or guarantee for a loan."),
        v("u12v4", "mortgage", "a type of loan used to purchase or maintain a home, land, or other types of real estate. The borrower agrees to pay the lender over time, typically in regular payments divided into principal and interest. The property serves as collateral."),
        v("u12v5", "overdraft", "Something that occurs when you make a purchase or write a check for an amount that exceeds your checking account's available balance."),
        v("u12v6", "current account", "an account at a bank against which checks can be drawn by the account depositor; a checking account."),
        v("u12v7", "savings account", "a deposit account that generally earns higher interest than an interest-bearing checking account. It limits the number of certain transfers or withdrawals each statement cycle."),
        v("u12v8", "deposit account", "a bank account maintained by a financial institution in which a customer can deposit and withdraw money."),
        v("u12v9", "solvency", "When banks have enough money to cover potential losses."),
        v("u12v10", "commercial banks", "financial intermediaries with a government license to make loans and issue deposits, including deposits against which cheques can be written."),
        v("u12v11", "clearing system", "a set of arrangements in which debts between banks are settled by adding up all the transactions in a given period and paying only the net amounts needed to balance inter-bank accounts."),
      ],
      questions: [
        q("u12q1", "Liquidity is available cash, and how easily other assets can be turned into what?", "cash"),
        q("u12q2", "Collateral acts as what for a loan?", "a security or guarantee | security | a guarantee"),
        q("u12q3", "A mortgage is typically repaid in payments divided into principal and what?", "interest"),
        q("u12q4", "An overdraft happens when a payment exceeds what?", "the available balance | your checking account's available balance"),
        q("u12q5", "A current account is also called what?", "a checking account | checking account"),
        q("u12q6", "Solvency means banks have enough money to cover what?", "potential losses"),
        q("u12q7", "A clearing system pays only the net amounts needed to balance what?", "inter-bank accounts"),
      ],
    },
    {
      id: "u13",
      label: "Unit 13: Accounting and Financial Statements",
      vocab: [
        v("u13v1", "cost accounting", "calculating all the expenses involved in producing something, including materials, labour, and all other expenses."),
        v("u13v2", "tax accounting", "calculating how much an individual or a company will have to pay to the local and national governments, and trying to reduce this to a minimum."),
        v("u13v3", "auditing", "inspecting and reporting on accounts and financial records."),
        v("u13v4", "accounting", "preparing financial statements showing income and expenditure, assets and liabilities."),
        v("u13v5", "management accounting | managerial accounting", "providing information that will allow a business to make decisions, plan future operations and develop business strategies."),
        v("u13v6", "creative accounting", "using all available accounting procedures and tricks to disguise the true financial position of a company."),
        v("u13v7", "bookkeeping", "writing down the details of transactions (debits and credits)."),
        v("u13v8", "cash flow statement", "a statement giving details of money coming into and leaving the business, divided into day-to-day operations, investing and financing."),
        v("u13v9", "income statement | profit and loss statement | profit and loss account", "a statement showing the difference between the revenues and expenses of a period."),
        v("u13v10", "balance sheet | statement of financial position", "a statement showing the value of a business's assets, its liabilities, and its capital or shareholders' equity."),
      ],
      questions: [
        q("u13q1", "Cost accounting calculates all the expenses involved in what?", "producing something"),
        q("u13q2", "Auditing inspects and reports on what?", "accounts and financial records"),
        q("u13q3", "Creative accounting tries to disguise what?", "the true financial position of a company"),
        q("u13q4", "Bookkeeping writes down debits and what?", "credits"),
        q("u13q5", "A cash flow statement shows money coming into and doing what?", "leaving the business"),
        q("u13q6", "An income statement shows the difference between revenues and what?", "expenses"),
        q("u13q7", "A balance sheet shows assets, liabilities, and what else?", "capital | shareholders' equity | capital or shareholders' equity"),
      ],
    },
    {
      id: "u14",
      label: "Unit 14: The Business Cycle",
      vocab: [
        v("u14v1", "business cycle", "a model showing the increases and decreases in a nation's real GDP over time. It typically shows an increase in real GDP over the long run, combined with short-run fluctuations in output."),
        v("u14v2", "expansion", "the phase of the business cycle during which output is increasing."),
        v("u14v3", "recession", "the phase of the business cycle during which output is falling."),
        v("u14v4", "depression", "a deep and prolonged recession."),
        v("u14v5", "peak", "the turning point in the business cycle between an expansion and a contraction. Output has stopped increasing and begins to decrease."),
        v("u14v6", "trough", "the turning point in the business cycle between a recession and an expansion. Output that had been falling begins to rise."),
        v("u14v7", "downturn", "a decline in economic activity."),
        v("u14v8", "upturn", "an increase in economic activity."),
        v("u14v9", "expectations", "beliefs about what will happen in the future."),
        v("u14v10", "consumption", "purchasing and using goods and services."),
        v("u14v11", "balance of payments", "the difference between the funds a country receives and those it pays for all international transactions."),
        v("u14v12", "gross domestic product | GDP", "the total market value of all the goods and services produced in a country during a given period."),
        v("u14v13", "demand", "the willingness and ability of consumers to purchase goods and services."),
        v("u14v14", "supply", "the willingness and ability of businesses to offer goods or services for sale."),
        v("u14v15", "boom", "A long period of expansion."),
      ],
      questions: [
        q("u14q1", "During an expansion, output is doing what?", "increasing"),
        q("u14q2", "During a recession, output is doing what?", "falling"),
        q("u14q3", "A depression is what kind of recession?", "a deep and prolonged recession | deep and prolonged"),
        q("u14q4", "A peak is the turning point between an expansion and what?", "a contraction"),
        q("u14q5", "A trough is the turning point between a recession and what?", "an expansion"),
        q("u14q6", "What is a decline in economic activity called?", "a downturn | downturn"),
        q("u14q7", "GDP is the total market value of all goods and services produced where?", "in a country"),
        q("u14q8", "What is a long period of expansion called?", "a boom | boom"),
      ],
    },
    {
      id: "u15",
      label: "Unit 15: Corporate Social Responsibility",
      vocab: [
        v("u15v1", "ethical standard", "a rule for moral behaviour in a particular area."),
        v("u15v2", "ethical behaviour", "doing things that are morally right."),
        v("u15v3", "ethical lapse", "temporary failure to act in the correct way."),
        v("u15v4", "ethical dilemma", "a choice between two actions that might both be morally wrong."),
        v("u15v5", "ethical stance", "a stated opinion about the right thing to do in a particular situation."),
        v("u15v6", "ethical issue", "an area where moral behaviour is important."),
        v("u15v7", "business ethics", "Standards of business behaviour that promote human welfare and the good."),
        v("u15v8", "corporate social responsibility | CSR", "A company's commitment to improving or enhancing community well-being through discretionary contributions of corporate resources."),
      ],
      questions: [
        q("u15q1", "An ethical lapse is a temporary failure to do what?", "act in the correct way"),
        q("u15q2", "An ethical dilemma is a choice between two actions that might both be what?", "morally wrong"),
        q("u15q3", "Business ethics promote human welfare and what?", "the good"),
        q("u15q4", "Name the five dimensions of CSR.", "Environment, Social, Economic, Stakeholder, and Volunteerism"),
        q("u15q5", "CSR improves community well-being through what kind of contributions?", "discretionary contributions of corporate resources | discretionary contributions"),
      ],
    },
    {
      id: "u16",
      label: "Unit 16: Efficiency and Employment",
      vocab: [
        v("u16v1", "job insecurity", "The fear that you might lose your job."),
        v("u16v2", "employability", "The extent to which a person has skills that employers want."),
        v("u16v3", "downsizing", "Decreasing the number of permanent employees."),
        v("u16v4", "core", "The central part of something, for example a company's workforce."),
        v("u16v5", "efficiency", "a situation in which a person, company, factory, etc. uses resources such as time, materials, or labour well, without wasting any."),
        v("u16v6", "rationalization", "to make a company or way of working more effective, usually by combining or stopping particular activities, or by employing fewer people."),
        v("u16v7", "redundancy package", "all the payments and advantages that a company gives to workers who have lost their jobs because they are no longer needed."),
        v("u16v8", "restructuring", "to organize a company, business, or system in a new way to make it operate more effectively."),
        v("u16v9", "delocalization", "to move the location of an enterprise."),
      ],
      questions: [
        q("u16q1", "Job insecurity is the fear that you might do what?", "lose your job"),
        q("u16q2", "Downsizing decreases the number of what?", "permanent employees"),
        q("u16q3", "Efficiency means using resources well without doing what?", "wasting any | wasting them"),
        q("u16q4", "A redundancy package is given to workers who have lost their jobs because they are what?", "no longer needed"),
        q("u16q5", "Delocalization means moving what?", "the location of an enterprise"),
        q("u16q6", "In the post-office case, the restructuring would save how much a year in salaries?", "€200 million | 200 million euros"),
      ],
    },
    {
      id: "u17",
      label: "Unit 17: International Trade",
      vocab: [
        v("u17v1", "international trade", "Purchase, sale, or exchange of goods and services across national borders."),
        v("u17v2", "free trade", "a trade policy that does not restrict imports or exports. It can also be understood as the free market idea applied to international trade."),
        v("u17v3", "protectionism", "the economic policy of restraining trade between nations, through methods such as tariffs on imported goods, restrictive quotas, and other regulations designed to discourage imports and prevent foreign take-over of local markets and companies."),
        v("u17v4", "trade barriers", "Government laws, regulations, policies or practices that either protect domestic products from foreign competition or artificially stimulate exports of particular domestic products."),
        v("u17v5", "tariff", "A duty or tax levied upon goods transported from one customs area to another. Tariffs raise the prices of imported goods, making them generally less competitive."),
        v("u17v6", "quota", "Restriction on the amount of a good that can enter or leave a country during a certain period of time."),
        v("u17v7", "absolute advantage", "Ability of a nation to produce a good more efficiently than any other nation."),
        v("u17v8", "comparative advantage", "Ability of a nation to produce a good more efficiently than it produces any other good."),
        v("u17v9", "infant industry", "a new industry, which in its early stages experiences relative difficulty or is absolutely incapable of competing with established competitors abroad."),
        v("u17v10", "strategic industry", "an industry which is essential for the promotion or stabilization of the growth of the locality in which that industry is situated."),
      ],
      questions: [
        q("u17q1", "International trade is the purchase, sale, or exchange of goods and services across what?", "national borders"),
        q("u17q2", "Free trade does not restrict what?", "imports or exports"),
        q("u17q3", "A tariff raises the prices of what?", "imported goods"),
        q("u17q4", "A quota restricts the amount of a good that can enter or leave a country during what?", "a certain period of time"),
        q("u17q5", "Absolute advantage is the ability to produce a good more efficiently than whom?", "any other nation"),
        q("u17q6", "An infant industry has difficulty competing with whom?", "established competitors abroad"),
        q("u17q7", "Ha-Joon Chang compares protection of a new industry to protecting whom?", "his son | a child | his young son"),
      ],
    },
  ];
  for (const unit of units) {
    const pack = PRACTICE[unit.id];
    if (!pack) continue;
    unit.clozes = pack.clozes;
    unit.questions = pack.questions;
    const extra = EXTRA_VOCAB[unit.id];
    if (extra?.length) unit.vocab = [...unit.vocab, ...extra];
  }
  return units;
}
