import type { Question, Vocab } from "@/lib/workbook";

function c(id: string, word: string, sentence: string): Vocab {
  return { id, word, sentence };
}

function s(id: string, prompt: string, answer: string, accept: string): Question {
  return { id, prompt, answer, accept };
}

export const PRACTICE: Record<string, { clozes: Vocab[]; questions: Question[] }> = {
  u01: {
    clozes: [
      c("u01c1", "set objectives", "After an organization has set objectives, it has to make sure that it achieves them."),
      c("u01c2", "allocate", "Managers have to find the best way to allocate all the human, physical and capital resources available to them."),
      c("u01c3", "resources", "Managers have to find the best way to allocate all the human, physical and capital resources available to them."),
      c("u01c4", "perform tasks", "Some people perform tasks better on their own while others work better in teams."),
      c("u01c5", "supervise", "Managers supervise the work of their subordinates and try to develop their abilities."),
      c("u01c6", "subordinates", "Managers supervise the work of their subordinates and try to develop their abilities."),
      c("u01c7", "measure", "Managers measure the performance of their staff to see whether they are reaching their targets."),
      c("u01c8", "performance", "Managers measure the performance of their staff to see whether they are reaching their targets."),
      c("u01c9", "deal with", "Top managers have to be prepared to deal with crises if they occur and then have to make decisions."),
      c("u01c10", "understand", "Actually, management as we understand it today is a fairly recent idea."),
      c("u01c11", "commercialize", "They perceive opportunities to commercialize new technologies and products that will serve the market better."),
      c("u01c12", "risk", "They are happy to risk their own or other people's capital."),
      c("u01c13", "work out", "Managers have to set objectives for their organization, and then work out how to achieve them."),
      c("u01c14", "communicate", "They need to communicate the organization's objectives to the people responsible for attaining them."),
      c("u01c15", "contribute", "They have to motivate their staff to work well, to be productive, and to contribute something to the organization."),
    ],
    questions: [
      s("u01q1", "What are the main differences between a manager and a leader? (Max. 30 words)", "Managers have formal power from their position and uphold the status quo. Leaders rely on personal qualities, their influence is temporary, and they challenge the status quo.", "position & status quo & personal & challenge"),
      s("u01q2", "What are the five functions of management?", "The five functions are planning, organizing, coordinating, commanding and controlling.", "planning & organizing & coordinating & commanding & controlling"),
      s("u01q3", "What does planning involve, and what must managers also plan for?", "Planning involves setting aims or targets. Managers must also plan for physical, human and financial resources.", "aims | targets & resources"),
      s("u01q4", "What is the difference between an entrepreneur and a manager?", "Entrepreneurs are alert to undiscovered profit opportunities and start a business. A manager is needed to run it in the long term.", "profit & manager"),
      s("u01q5", "What is used to show authority and ensure specialization?", "An organizational chart is used to show authority and ensure specialization.", "organizational chart"),
      s("u01q6", "What does coordinating mean?", "Coordinating means bringing together different individuals and departments, such as Marketing and Production.", "bringing together"),
    ],
  },
  u02: {
    clozes: [
      c("u02c1", "pursue", "If these needs are not satisfied, people will not pursue other needs."),
      c("u02c2", "actualize", "The desire to develop as a person, to actualize one's potential, and to achieve the goals one has set for oneself."),
      c("u02c3", "achieve", "The desire to develop as a person, to actualize one's potential, and to achieve the goals one has set for oneself."),
      c("u02c4", "set", "Employees will only be motivated if they are able to realize the goals one has set for oneself."),
      c("u02c5", "earn", "The more money one has, the less motivating it is to earn more."),
      c("u02c6", "enrichment", "They tried job enrichment to make the work better and more enjoyable."),
      c("u02c7", "outcome", "Task identity is the degree to which a job has a visible outcome."),
      c("u02c8", "autonomy", "Workers want more autonomy when they schedule work and choose their own procedures."),
      c("u02c9", "significance", "The job matters because it has real significance for the work of other people."),
      c("u02c10", "enlargement", "The manager used job enlargement and combined several tasks into one assignment."),
      c("u02c11", "rotation", "The factory uses job rotation and moves employees from one job to another."),
    ],
    questions: [
      s("u02q1", "Summarise Frederick Herzberg's Two-Factor Theory in a maximum of 40 words.", "Herzberg says people have hygiene factors and motivators. Hygiene factors such as pay prevent dissatisfaction but do not motivate. Motivators such as responsibility allow psychological growth.", "hygiene & motivat"),
      s("u02q2", "Please tell me the fundamental difference between Theory X and Theory Y in a maximum of 20 words.", "Theory X says people dislike work and need external control. Theory Y says people are motivated by internal factors.", "external & internal"),
      s("u02q3", "What are the three ways to motivate workers to be more committed to their jobs?", "The three ways are job rotation, job enlargement and job enrichment.", "job rotation & job enlargement & job enrichment"),
      s("u02q4", "What is job satisfaction?", "Job satisfaction is the enjoyment a worker gets from feeling that they have done a good job.", "enjoyment | good job"),
      s("u02q5", "Name Maslow's five categories of needs.", "They are physiological needs, safety needs, love and belonging needs, esteem needs, and self-actualization needs.", "physiological & safety & esteem & self-actualization"),
      s("u02q6", "What are hygiene factors?", "Hygiene factors are the factors that must be present in the workplace to prevent job dissatisfaction.", "dissatisfaction"),
    ],
  },
  u03: {
    clozes: [
      c("u03c1", "into more concrete objectives", "Operational planning translates general goals into more concrete objectives."),
      c("u03c2", "into functional departments", "It is usual to divide an organization into functional departments."),
      c("u03c3", "geographical regions", "Some companies are organized according to geographical regions."),
      c("u03c4", "major strategy issues", "The Board gets involved in major strategy issues."),
      c("u03c5", "a direction for the company", "Senior managers set a direction for the company."),
      c("u03c6", "first-line manager", "Subordinates work under the supervision of a first-line manager."),
      c("u03c7", "chain of command", "A clear line or chain of command runs down the hierarchy, so that all employees know who their superior is."),
      c("u03c8", "matrix management", "One solution to this problem is matrix management, in which people report to more than one superior."),
      c("u03c9", "staff position", "This is an example of a staff position: its holder has no line authority, and is not integrated into the chain of command."),
      c("u03c10", "delegated", "People at lower levels are unable to make important decisions, unless responsibilities have been explicitly delegated."),
    ],
    questions: [
      s("u03q1", "What does Wikinomics mean? (Max. 20 words)", "Wikinomics is mass collaboration with outsiders, who are paid for ideas that improve an operation.", "collaboration | cooperate & outside | outsiders & ideas"),
      s("u03q2", "What are the pros and cons of matrix management?", "People can report to more than one superior and deal directly across departments. The disadvantage is that the matrix can become quite complex.", "more than one & complex"),
      s("u03q3", "What is span of control?", "Span of control is the number of subordinates working directly under a manager.", "subordinates"),
      s("u03q4", "What is delegation?", "Delegation means giving a subordinate the authority to perform a particular task.", "authority"),
      s("u03q5", "What is decentralization?", "Decentralization means taking decisions away from the centre of an organization, away from the Head Office.", "head office | centre"),
      s("u03q6", "What is outsourcing?", "Outsourcing means transferring internal functions or jobs to outside suppliers instead of doing them in-house.", "outside | suppliers"),
    ],
  },
  u04: {
    clozes: [
      c("u04c1", "dimensions", "Power distance is one of the important cultural dimensions that Hofstede identified."),
      c("u04c2", "low-power distance", "Sweden is a low-power distance culture."),
      c("u04c3", "accessible", "Managers are accessible and approachable and employees are involved in decision-making."),
      c("u04c4", "high-power distance", "France is a high-power distance culture. Managers are usually more distant and remote."),
      c("u04c5", "distant", "Employees may feel quite distant from their managers and show a lot of deference to them."),
      c("u04c6", "hierarchical", "This Swedish company is not very hierarchical, with only three management layers."),
      c("u04c7", "forms of address", "Some languages have many forms of address that you use to indicate how familiar you are with someone."),
      c("u04c8", "corporate", "In this company the corporate culture used to be very formal: managers could only wear white shirts."),
      c("u04c9", "long-hours", "They say that if you go home at 5.30 you are not doing the job properly. That is a long-hours culture."),
      c("u04c10", "sales", "When selling is seen as the most important thing in an organization, it has a sales culture."),
    ],
    questions: [
      s("u04q1", "How does the Lewis Model, developed by Richard D. Lewis in the 1990s, divide human behavior and communication? (Max. 30 words)", "The Lewis Model divides people by behaviour, not nationality, into three categories: Linear-active, Multi-active and Reactive.", "linear-active & multi-active & reactive"),
      s("u04q2", "What is power distance? (Max. 15 words)", "Power distance measures how people cope with inequality and relate to more powerful individuals.", "inequality"),
      s("u04q3", "What is a high-context culture? (Max. 15 words)", "Rules are shown through context, such as body language and tone, and are usually not written.", "context & not written | body language"),
      s("u04q4", "What is a low-context culture?", "In a low-context culture, most communication is verbal and the rules are written or stated directly.", "verbal | written"),
      s("u04q5", "What is glocalization?", "Glocalization is a product or service developed globally but adjusted for the user in a local market.", "global & local"),
      s("u04q6", "What is culture?", "Culture is the complex system of values, traits, morals and customs shared by a society.", "values | customs"),
    ],
  },
  u05: {
    clozes: [
      c("u05c1", "vacancy", "When a company has a vacancy for a new member of staff, it usually advertises the post."),
      c("u05c2", "internally", "It advertises the post internally, for example in the company magazine, or externally in a newspaper."),
      c("u05c3", "externally", "It advertises the post internally, for example in the company magazine, or externally in a newspaper."),
      c("u05c4", "job description", "A job advertisement has to give an accurate job description of the job and what it requires from the applicants."),
      c("u05c5", "qualifications", "These requirements might include qualifications, work experience, and certain personal qualities."),
      c("u05c6", "experience", "These requirements might include qualifications, work experience, and certain personal qualities."),
      c("u05c7", "CV", "The advertisement will usually ask people to send their CV with a covering letter."),
      c("u05c8", "covering letter", "People interested in the post send their CV with a covering letter, or a letter of introduction."),
      c("u05c9", "short-list", "The managers prepare a short-list of possible candidates who will be invited for an interview."),
      c("u05c10", "psychometric", "Applicants may also take psychometric tests, which look at psychological traits."),
      c("u05c11", "job description", "Sometimes the company examines the job description for the post, and decides that it no longer needs to be filled."),
      c("u05c12", "promoted", "The company will replace the person who resigns with an internal candidate who can be promoted to the job."),
      c("u05c13", "agency", "Or it will advertise the position in newspapers, or engage an employment agency to do so."),
      c("u05c14", "headhunters", "For senior positions, companies sometimes use the services of a firm of headhunters."),
      c("u05c15", "apply", "To reply to an advertisement is to apply for a job; you become an applicant or a candidate."),
      c("u05c16", "applicant", "To reply to an advertisement is to apply for a job; you become an applicant or a candidate."),
    ],
    questions: [
      s("u05q1", "What are the typical requirements in a job description?", "A job description states responsibilities and duties. Typical requirements also include educational qualifications, experience, special skills or aptitude, and personal characteristics.", "duties | responsibilities & qualifications & experience & skills | aptitude"),
      s("u05q2", "What is the difference between a job description and a job specification?", "A job description outlines duties. A job specification outlines the requirements, qualifications and expertise for the job.", "duties & qualifications"),
      s("u05q3", "What is internal recruitment?", "Internal recruitment is when a vacancy is filled by someone who is already an existing employee.", "existing employee"),
      s("u05q4", "What is external recruitment?", "External recruitment is when a vacancy is filled by someone who is not an existing employee.", "not an existing | new to the business | not already"),
      s("u05q5", "What is induction training?", "Induction training explains the business's activities, customs and procedures and introduces new employees to their fellow workers.", "new employee | fellow"),
      s("u05q6", "What is the difference between on-the-job and off-the-job training?", "On-the-job training is watching a more experienced worker. Off-the-job training is away from the workplace, usually by specialist trainers.", "experienced & away"),
    ],
  },
  u06: {
    clozes: [
      c("u06c1", "sole trader", "The simplest form of business is the individual proprietorship or sole trader, for example a shop owned by a single person."),
      c("u06c2", "partnership", "If several individuals wish to go into business together they can form a partnership."),
      c("u06c3", "losses", "Partners generally contribute equal capital, have equal authority, and share profits or losses."),
      c("u06c4", "liability", "In many countries, lawyers and doctors can only form partnerships with unlimited liability for debts."),
      c("u06c5", "bankruptcy", "In the case of bankruptcy, a partner with a personal fortune can lose it all."),
      c("u06c6", "corporations", "The majority of businesses are limited companies, which in the US are called corporations."),
      c("u06c7", "creditors", "If the assets do not cover the debts, creditors do not get their money back."),
      c("u06c8", "shares", "Private limited companies cannot offer shares to the public."),
      c("u06c9", "prospectus", "A public limited company can publish a prospectus and offer its shares for sale on the stock market."),
      c("u06c10", "registered", "The American equivalent of a public limited company is one registered by the Securities and Exchange Commission."),
    ],
    questions: [
      s("u06q1", "Name five sectors of the economy.", "Primary, secondary, tertiary, quaternary and quinary.", "primary & secondary & tertiary & quaternary & quinary"),
      s("u06q2", "Give a definition of each.", "Primary extracts natural resources. Secondary manufactures goods. Tertiary provides services. Quaternary covers information services such as computing and R&D. Quinary covers top-level decision making.", "natural resources | raw materials & manufactur & services & information & decision"),
      s("u06q3", "What are the types of business organizations?", "Sole traders, partnerships, private limited companies, public limited companies, franchises and joint ventures.", "sole trader & partnership & private limited & public limited & franchise & joint venture"),
      s("u06q4", "What is the difference between limited and unlimited liability?", "Limited liability stops at the amount invested. With unlimited liability, owners can be held responsible for the debts of the business.", "invested & debts"),
      s("u06q5", "What is a mixed economy?", "A mixed economy has both a private sector and a public sector.", "private & public"),
      s("u06q6", "What is privatisation?", "Privatisation is the sale of state-owned assets, such as public corporations, to the private sector.", "private sector | sale"),
    ],
  },
  u07: {
    clozes: [
      c("u07c1", "lead time", "Unless our supplier reduces its lead time, we will have to radically change the way we operate."),
      c("u07c2", "purchasing power", "The recession has led to a drop in overall purchasing power, which means that we will have to reduce output."),
      c("u07c3", "optimum capacity", "We are currently operating at optimum capacity, which means that we can afford to keep prices lower."),
      c("u07c4", "assembly line", "She works on an assembly line in a factory that makes electronic goods."),
      c("u07c5", "finished goods", "You can view our range of finished goods in the showroom."),
      c("u07c6", "product recall", "The company had to put out a product recall to its customers when several dangerous faults were discovered."),
      c("u07c7", "offshore manufacturing", "We will be unable to compete unless we reduce our costs by taking advantage of offshore manufacturing."),
      c("u07c8", "planned obsolescence", "Our company builds planned obsolescence into most of its electronic products."),
      c("u07c9", "supply chain", "We are an important part of the supply chain for the industry."),
      c("u07c10", "zero defects", "None of our products are allowed to leave the factory unless there are zero defects present."),
      c("u07c11", "raw materials", "The manufacture of most items relies on a reliable source of raw materials such as wood, iron ore or crude petroleum."),
      c("u07c12", "random sampling", "We usually find that random sampling gives us a good idea of quality."),
    ],
    questions: [
      s("u07q1", "What is lean production?", "Lean production uses techniques to cut waste of resources, including time, and to remove activities that do not add value for the customer.", "waste"),
      s("u07q2", "What are the types of waste that occur in production?", "The seven wastes are overproduction, waiting, transportation, unnecessary inventory, motion, over-processing and defects.", "overproduction & waiting & transportation & inventory & motion & over-processing | overprocessing & defects"),
      s("u07q3", "How do you apply the concept of Kaizen to your daily life?", "Kaizen is continuous improvement from workers' own ideas, not new equipment. In daily life it means small regular changes that remove wasted time or movement.", "continuous improvement & waste"),
      s("u07q4", "What is JIT? (Max. 20 words)", "JIT reduces or eliminates inventories. Materials and finished goods are made or delivered just in time to be used.", "inventor"),
      s("u07q5", "What is the difference between job production and flow production?", "Job production makes items one at a time. Flow production makes large quantities of identical goods in a continuously moving process.", "one at a time & identical"),
      s("u07q6", "What does Kaizen mean?", "Kaizen means continuous improvement. The ideas come from the workers themselves, and the focus is on eliminating waste.", "continuous improvement & workers"),
    ],
  },
  u08: {
    clozes: [
      c("u08c1", "chain", "Logistics management is that part of supply chain management that plans, implements and controls the flow of goods."),
      c("u08c2", "origin", "It controls the flow of goods, services and information between the point of origin and the point of consumption."),
      c("u08c3", "outbound", "Logistics management activities usually include inbound and outbound transportation management."),
      c("u08c4", "service", "The logistics function also includes sourcing and procurement, packaging, and customer service."),
      c("u08c5", "operational", "It is involved in all levels of planning and execution: strategic, operational and tactical."),
      c("u08c6", "activities", "Logistics management coordinates all logistics activities, as well as integrating them with marketing, sales and finance."),
      c("u08c7", "technology", "It also integrates logistics activities with information technology."),
      c("u08c8", "ensuring", "Customer service means ensuring the right product is at the right place at the right time."),
      c("u08c9", "forecasting", "The planners use demand forecasting to decide how many goods to order in the future."),
      c("u08c10", "handling", "Inventory management and materials handling keep the supply chain flowing, with no bottlenecks."),
      c("u08c11", "balancing", "This is done by balancing the quantity of items at different locations and different stages in the process."),
      c("u08c12", "negotiating", "Purchasing means negotiating with suppliers about price, availability and quality."),
      c("u08c13", "warehousing", "The company spent more on warehousing so goods could be stored and then distributed."),
    ],
    questions: [
      s("u08q1", "What are the pros and cons of push and pull strategies in logistics? (Max. 40 words)", "Push uses forecasts, so goods are ready, but inventory and waste can rise. Pull follows actual demand, so inventory falls, but production waits for orders.", "forecast & demand & inventory"),
      s("u08q2", "How do you apply the concept of push and pull strategies in logistics to your real life? (Max. 40 words)", "Push is buying from a forecast, such as food for the week before you need it. Pull is buying only when something has run out, which keeps less stock at home.", "push & pull"),
      s("u08q3", "What is reverse logistics?", "Reverse logistics brings goods back to the manufacturer because of defects or for recycling.", "defects | recycling"),
      s("u08q4", "What is the difference between inbound and outbound logistics?", "Inbound logistics brings raw materials from suppliers to producers. Outbound logistics moves finished products to buyers and consumers.", "suppliers & finished"),
      s("u08q5", "What is a push strategy?", "A push strategy produces and distributes goods based on forecasted demand, even if customers have not ordered them yet.", "forecast"),
      s("u08q6", "What is a pull strategy?", "A pull strategy lets actual customer demand drive production, which minimizes inventory and reduces waste.", "demand & inventory | waste"),
    ],
  },
  u09: {
    clozes: [
      c("u09c1", "costly", "A lack of quality can be more costly than achieving high quality. As Philip Crosby puts it, quality is free."),
      c("u09c2", "expenses", "There are many expenses that result from production that is not 100 percent perfect, such as inspecting, testing and reworking."),
      c("u09c3", "guarantee", "Those costs include replacing products in accordance with a guarantee and dealing with complaints."),
      c("u09c4", "defects", "Management should design a system which excludes defects, so that every worker gets it right the first time."),
      c("u09c5", "resented", "Quality at the source removes the over-the-shoulder inspection that is usually resented by workers."),
      c("u09c6", "permanent", "Many large Japanese companies, especially those guaranteeing permanent employment, have been able to attain high quality."),
      c("u09c7", "relationships", "High quality also depends on the long-term nature of the relationships among employees, suppliers and customers."),
      c("u09c8", "variations", "If there are problems with quality variations, the group will try to identify their sources."),
      c("u09c9", "individualistic", "Quality circles have been less successful in the more individualistic cultures of America and Europe."),
      c("u09c10", "benchmarking", "Even if the current quality level appears perfect, the company should still look for improvement and engage in benchmarking."),
    ],
    questions: [
      s("u09q1", "What is quality?", "Quality means producing a good or a service which meets customer expectations.", "customer expectations | expectations"),
      s("u09q2", "What is the difference between quality control and quality assurance?", "Quality control checks quality at the end of the process. Quality assurance checks standards throughout the process.", "end & throughout"),
      s("u09q3", "What is Total Quality Management?", "Total Quality Management is the continuous improvement of products and processes by focusing on quality at each stage of production.", "continuous improvement & each stage"),
      s("u09q4", "When does quality control take place?", "Quality control takes place at the end of the production process.", "end"),
      s("u09q5", "When does quality assurance take place?", "Quality assurance takes place throughout the production process.", "throughout"),
      s("u09q6", "Whose expectations must a quality product meet?", "A quality product must meet customer expectations.", "customer"),
    ],
  },
  u10: {
    clozes: [
      c("u10c1", "making a loss", "In the Introduction stage the product has low sales and will still be making a loss."),
      c("u10c2", "early adopters", "If the product has few competitors, a skimming price strategy can be used: a high price for early adopters, which is then gradually lowered."),
      c("u10c3", "similar offerings", "In the Growth phase, competitors are attracted to the market with similar offerings."),
      c("u10c4", "advertising budgets", "In the growth phase the company increases its advertising budgets to build the brand."),
      c("u10c5", "differentiate", "In the Maturity phase, producers attempt to differentiate products and brands are key to this."),
      c("u10c6", "reaches saturation", "Price wars and competition occur as the market reaches saturation."),
      c("u10c7", "consumer tastes", "In the Decline phase the product is starting to look old-fashioned or consumer tastes have changed."),
      c("u10c8", "withdrawn from the market", "There is intense price-cutting and many products are withdrawn from the market."),
      c("u10c9", "consumer needs", "Market research is the process by which a company collects information about consumer needs and preferences."),
      c("u10c10", "gaps in the market", "The information helps to identify market trends and spot gaps in the market."),
    ],
    questions: [
      s("u10q1", "What is a market leader?", "The market leader is the company with the largest market share.", "market share"),
      s("u10q2", "What is market segmentation?", "Market segmentation is dividing a market into distinct groups of buyers who have different requirements or buying habits.", "dividing | groups"),
      s("u10q3", "What is market share?", "Market share is a company's sales expressed as a percentage of total sales in the market.", "percentage"),
      s("u10q4", "What is the marketing mix?", "The marketing mix is the set of all the elements in a marketing programme, and the way a company integrates them.", "elements | programme"),
      s("u10q5", "What is a marketing strategy?", "A marketing strategy is a plan or principle designed to achieve marketing objectives.", "objectives"),
      s("u10q6", "What is the product life cycle?", "The product life cycle is the standard pattern of sales of a product over the period that it is marketed.", "sales"),
    ],
  },
  u11: {
    clozes: [
      c("u11c1", "endorses", "If a celebrity endorses a product, they say how good it is in advertisements."),
      c("u11c2", "hoardings", "Billboards, those large signs used for advertising, are often called hoardings in British English."),
      c("u11c3", "samples", "Manufacturers of toiletries and cosmetics frequently offer free samples for customers to try out their new products."),
      c("u11c4", "point-of-sale", "Advertising done at the place where a product is sold is called point-of-sale advertising."),
      c("u11c5", "sponsorship", "The company chose sponsorship of a sports event as a way to advertise."),
      c("u11c6", "word-of-mouth", "If you hear about a new product from a friend or relative, this is called word-of-mouth advertising."),
      c("u11c7", "commercials", "Outdoor advertising is growing rapidly because the cost of TV commercials has risen dramatically."),
      c("u11c8", "advertising agency", "Large companies tend to hire the services of an advertising agency."),
      c("u11c9", "budget", "The client company generally decides on its advertising budget, the amount of money it plans to spend."),
      c("u11c10", "brief", "It also provides a brief, or a statement of the objectives of the advertising."),
      c("u11c11", "media plan", "The choice of how and where to advertise, and in what proportions, is called a media plan."),
      c("u11c12", "target", "The set of customers whose needs a company plans to satisfy are known as the target market."),
      c("u11c13", "campaign", "The advertising of a particular product during a particular period of time is called an advertising campaign."),
      c("u11c14", "publicity", "Favourable mentions that are not paid for are called publicity."),
    ],
    questions: [
      s("u11q1", "What is an advertorial?", "An advertorial is a paid-for advertisement which includes editorial content, and it is marked so readers can tell it from real editorial.", "paid & editorial"),
      s("u11q2", "What is product placement?", "Product placement is paying for a branded product to be used by a character in a movie.", "movie | branded"),
      s("u11q3", "What is a USP?", "A USP, or unique selling proposition, is a highlighted benefit that makes a product stand out from rival brands.", "benefit | stand out"),
      s("u11q4", "What are demographics?", "Demographics describe an audience by facts such as age, gender, ethnicity or location.", "age | gender"),
      s("u11q5", "What are focus groups?", "Focus groups are small groups that represent a target audience and are paid to answer questions.", "target audience | paid"),
      s("u11q6", "What is an advertising campaign?", "An advertising campaign is a time-limited set of ads, across one or more media, that execute a central idea.", "central idea | ads"),
    ],
  },
  u12: {
    clozes: [
      c("u12c1", "legal tender", "Spain now uses the euro. Pesetas are no longer legal tender."),
      c("u12c2", "refund", "I bought a TV which doesn't work. I'll take it back to the shop to get a refund."),
      c("u12c3", "receipt", "In a shop, to get a refund, you usually have to show the receipt."),
      c("u12c4", "instalments", "I'm paying for my new car in 36 monthly instalments."),
      c("u12c5", "expenses", "I earn a lot of money, but I have a lot of expenses."),
      c("u12c6", "auction", "Famous paintings are usually sold by auction."),
      c("u12c7", "bid", "In an auction, the item is sold to the person who makes the highest bid."),
      c("u12c8", "foreign currency", "In Japan, the US dollar is a foreign currency."),
      c("u12c9", "deposits", "Commercial banks receive and hold deposits, and pay money according to customers' instructions."),
      c("u12c10", "wages", "Traditionally, factory workers were paid wages in cash on Fridays."),
      c("u12c11", "salary", "Non-manual workers usually receive a monthly salary in the form of a cheque or a transfer."),
      c("u12c12", "current account", "She keeps her salary in a current account, which pays little interest but lets her withdraw cash."),
      c("u12c13", "overdraft", "The bank agreed an overdraft so she can spend more than the balance, up to a fixed limit."),
      c("u12c14", "standing orders", "He pays the rent by standing orders, the same sum every month."),
      c("u12c15", "spread", "Banks make a profit from the spread between the interest rates they pay on deposits and those they charge on loans."),
    ],
    questions: [
      s("u12q1", "What is collateral?", "Collateral is anything that acts as a security or guarantee for a loan.", "security | guarantee"),
      s("u12q2", "What is a mortgage?", "A mortgage is a loan used to buy property. Payments are divided into principal and interest, and the property is the collateral.", "loan & collateral | property"),
      s("u12q3", "What is an overdraft?", "An overdraft occurs when you pay or write a check for more than the available balance of your account.", "balance"),
      s("u12q4", "What is liquidity?", "Liquidity is available cash, and how easily other assets can be turned into cash.", "cash"),
      s("u12q5", "What is the difference between a current account and a savings account?", "A current account is a checking account. A savings account generally earns higher interest and limits some withdrawals.", "checking | checks & interest"),
      s("u12q6", "What is a clearing system?", "A clearing system adds up debts between banks in a period and pays only the net amounts needed to balance inter-bank accounts.", "net"),
    ],
  },
  u13: {
    clozes: [
      c("u13c1", "bookkeeping", "She spent the morning on bookkeeping, writing down every debit and every credit."),
      c("u13c2", "auditing", "The firm is auditing the accounts to make sure the records are true and honest."),
      c("u13c3", "creative accounting", "They used creative accounting to disguise the true financial position of the company."),
      c("u13c4", "budget", "The manager prepared a budget showing the income and expenditure expected next year."),
      c("u13c5", "assets", "The balance sheet lists assets such as cash, buildings and machines on one side."),
      c("u13c6", "liabilities", "It also lists liabilities, the money the company will have to pay in the future."),
      c("u13c7", "debit", "The payment they made was entered as a debit in the account."),
      c("u13c8", "credit", "The payment they received was entered as a credit in the account."),
      c("u13c9", "intangible", "A brand name is an intangible asset because you cannot touch it."),
      c("u13c10", "forensic", "The court asked for forensic accounting because illegal activity was suspected."),
    ],
    questions: [
      s("u13q1", "What is the difference between bookkeeping and accounting?", "Bookkeeping writes down debits and credits. Accounting prepares financial statements showing income, expenditure, assets and liabilities.", "debits | credits & statements | assets"),
      s("u13q2", "What is creative accounting?", "Creative accounting uses accounting procedures and tricks to disguise the true financial position of a company.", "disguise"),
      s("u13q3", "What does an income statement show?", "An income statement shows the difference between the revenues and the expenses of a period.", "revenues & expenses"),
      s("u13q4", "What does a balance sheet show?", "A balance sheet shows assets, liabilities, and capital or shareholders' equity.", "assets & liabilities"),
      s("u13q5", "What is auditing?", "Auditing means inspecting and reporting on accounts and financial records.", "accounts | records"),
      s("u13q6", "What is management accounting for?", "Management accounting provides information so a business can make decisions, plan future operations and develop strategies.", "decisions"),
    ],
  },
  u14: {
    clozes: [
      c("u14c1", "policy-makers", "What can central bankers and government policy-makers do? Can they prevent a contraction from turning into a recession?"),
      c("u14c2", "new borrowing", "For companies and individuals without existing loans, new borrowing becomes less expensive when interest rates are cut."),
      c("u14c3", "side-effects", "Lowering rates takes two or three quarters to benefit an economy, and it does also have unfortunate side-effects."),
      c("u14c4", "tax cuts", "The government used tax cuts so that people would have more money to spend."),
      c("u14c5", "government debt", "The problem arises when these measures lead to high levels of government debt. Eventually that debt will have to be repaid."),
      c("u14c6", "labour market", "Reforms include measures to enhance competition, to liberalize the labour market, and to make it easier to start a new business."),
    ],
    questions: [
      s("u14q1", "What is the difference between a recession and a depression?", "A recession is the phase when output is falling. A depression is a deep and prolonged recession.", "falling & prolonged | deep"),
      s("u14q2", "What is a peak in the business cycle?", "A peak is the turning point between an expansion and a contraction, when output stops increasing and begins to decrease.", "expansion & contraction | decrease"),
      s("u14q3", "What is a trough?", "A trough is the turning point between a recession and an expansion, when output that had been falling begins to rise.", "recession & expansion"),
      s("u14q4", "What is GDP?", "GDP is the total market value of all the goods and services produced in a country during a given period.", "market value | goods and services"),
      s("u14q5", "What is the difference between demand and supply?", "Demand is the willingness and ability of consumers to purchase goods. Supply is the willingness and ability of businesses to offer goods for sale.", "consumers & businesses"),
      s("u14q6", "What is a boom?", "A boom is a long period of expansion.", "expansion"),
    ],
  },
  u15: {
    clozes: [
      c("u15c1", "above board", "His lawyers have argued that the transactions were completely above board and approved by the other directors."),
      c("u15c2", "integrity", "The code of professional conduct requires directors to act with integrity and probity."),
      c("u15c3", "probity", "The code of professional conduct requires directors to act with integrity and probity."),
      c("u15c4", "misconduct", "It faces the most serious charges of misconduct yet brought against a big accountancy firm."),
      c("u15c5", "transparent", "We are totally transparent about the methods that we use, so it would be hard to hide the fact if the numbers were wrong."),
      c("u15c6", "accountable", "The city's officials ought to be held far more accountable than they are today for what they spend and how."),
    ],
    questions: [
      s("u15q1", "What is an ethical dilemma?", "An ethical dilemma is a choice between two actions that might both be morally wrong.", "morally wrong | two actions"),
      s("u15q2", "What is an ethical lapse?", "An ethical lapse is a temporary failure to act in the correct way.", "temporary"),
      s("u15q3", "What is corporate social responsibility?", "CSR is a company's commitment to improving community well-being through discretionary contributions of corporate resources.", "community | well-being"),
      s("u15q4", "Name the five dimensions of CSR.", "The five dimensions are Environment, Social, Economic, Stakeholder and Volunteerism.", "environment & social & economic & stakeholder & volunteerism"),
      s("u15q5", "What are business ethics?", "Business ethics are standards of business behaviour that promote human welfare and the good.", "welfare | the good"),
      s("u15q6", "What is an ethical stance?", "An ethical stance is a stated opinion about the right thing to do in a particular situation.", "opinion | right thing"),
    ],
  },
  u16: {
    clozes: [
      c("u16c1", "contract work", "As an IT specialist, I mainly do contract work for local companies, two or three months at a time."),
      c("u16c2", "job sharing", "Employers say job sharing is expensive, because two people instead of one means extra costs."),
      c("u16c3", "delayering", "Big companies abolished a lot of middle management positions by delayering in the 1980s."),
      c("u16c4", "outsourced", "Last year the firm outsourced its accounting and IT services to Indian companies."),
      c("u16c5", "delocalize", "We would never delocalize our manufacturing."),
      c("u16c6", "casual work", "Students often take casual work that is not regular or fixed."),
      c("u16c7", "downsizing", "The plant had fewer permanent employees after downsizing."),
      c("u16c8", "rightsizing", "They called the job cuts rightsizing, another way of saying downsizing."),
      c("u16c9", "redundant", "When they restructured the company, 1,000 people were made redundant."),
      c("u16c10", "flexible", "Hiring temporary staff is easy in a flexible labour market."),
    ],
    questions: [
      s("u16q1", "What is downsizing?", "Downsizing means decreasing the number of permanent employees.", "permanent employees | fewer employees"),
      s("u16q2", "What is a redundancy package?", "A redundancy package is all the payments and advantages given to workers who have lost their jobs because they are no longer needed.", "no longer needed | payments"),
      s("u16q3", "What is the difference between rationalization and delocalization?", "Rationalization makes a company more effective, often by employing fewer people. Delocalization moves the location of an enterprise.", "fewer | location"),
      s("u16q4", "What is efficiency?", "Efficiency means using resources such as time, materials or labour well, without wasting any.", "waste"),
      s("u16q5", "What is job insecurity?", "Job insecurity is the fear that you might lose your job.", "lose your job | fear"),
      s("u16q6", "What is employability?", "Employability is the extent to which a person has skills that employers want.", "skills"),
    ],
  },
  u17: {
    clozes: [
      c("u17c1", "customs", "Incoterms cover shipping costs and other costs such as insurance, customs duties, and ground handling."),
      c("u17c2", "handling", "Incoterms cover shipping costs and other costs such as insurance, customs duties, and ground handling."),
      c("u17c3", "premises", "A price quoted EXW means the seller makes the goods available at their own premises, and the buyer collects them there."),
      c("u17c4", "truck", "If the price is FAS, the seller also covers the cost of inland transport by truck or rail to the port of shipment."),
      c("u17c5", "loading", "The buyer pays for loading onto the ship plus all the costs from that point. With FOB, the seller pays for loading."),
      c("u17c6", "freight", "If the seller also pays the freight costs, further Incoterms such as CFR and CIF are used."),
      c("u17c7", "documentation", "With CFR the seller pays the freight costs and handles the export documentation, but does not pay the insurance."),
      c("u17c8", "transit", "With CFR the seller does not pay the insurance while the goods are in transit at sea."),
      c("u17c9", "terminal", "The buyer has responsibility for unloading fees and local storage at a terminal."),
      c("u17c10", "clearance", "With DDP, the seller also has to handle any customs clearance problems. The buyer has no additional costs."),
    ],
    questions: [
      s("u17q1", "What is the difference between free trade and protectionism?", "Free trade does not restrict imports or exports. Protectionism restrains trade through tariffs, quotas and other regulations.", "restrict & tariff"),
      s("u17q2", "What is the difference between a tariff and a quota?", "A tariff is a tax that raises the price of imported goods. A quota restricts the amount of a good that can enter or leave a country.", "tax | price & amount"),
      s("u17q3", "What is absolute advantage?", "Absolute advantage is the ability of a nation to produce a good more efficiently than any other nation.", "any other nation | more efficiently"),
      s("u17q4", "What is comparative advantage?", "Comparative advantage is the ability of a nation to produce a good more efficiently than it produces any other good.", "any other good"),
      s("u17q5", "What is an infant industry?", "An infant industry is a new industry that, in its early stages, cannot compete with established competitors abroad.", "new & abroad | competitors"),
      s("u17q6", "Why does Ha-Joon Chang compare protection to raising a child?", "He says a child sent to work too early never becomes a surgeon. A new industry also needs protection until it grows up.", "child | protection"),
    ],
  },
};

function v(id: string, word: string, sentence: string): Vocab {
  return { id, word, sentence };
}

export const EXTRA_VOCAB: Record<string, Vocab[]> = {
  u01: [
    v("u01x1", "strategy", "A plan for achieving success."),
    v("u01x2", "objective", "Something you plan to do or achieve."),
    v("u01x3", "innovation", "A new idea or method."),
    v("u01x4", "subordinate", "A person with a less important position in an organization."),
    v("u01x5", "consultant", "A person who provides expert advice to a company."),
    v("u01x6", "promotion", "When someone is raised to a higher or more important position."),
    v("u01x7", "crisis | crises", "A situation of danger or difficulty."),
    v("u01x8", "public sector", "The section of the economy under government control."),
  ],
  u02: [
    v("u02x1", "physiological needs", "The most basic human needs, such as food, water, air and sleep."),
    v("u02x2", "safety needs", "The need to be free from danger, physical pain, and the threat of losing one's job."),
    v("u02x3", "esteem needs", "The need for self-respect and to be respected by others."),
    v("u02x4", "self-actualization", "The desire to develop as a person and to realize one's potential."),
    v("u02x5", "incentive", "Something that encourages a worker to work harder, such as extra pay."),
    v("u02x6", "fringe benefits", "Advantages given with a job besides wages, such as a company car or free medical insurance."),
    v("u02x7", "commission", "Money paid to a salesperson as a percentage of the sales they make."),
    v("u02x8", "bonus", "Extra money paid to a worker for good performance or at the end of the year."),
    v("u02x9", "piece rate", "Pay that depends on the number of items a worker produces."),
    v("u02x10", "feedback", "Direct information a person receives about their performance."),
  ],
  u03: [
    v("u03x1", "line authority", "The right to command people directly below you in the hierarchy."),
    v("u03x2", "staff position", "A post whose holder helps someone else but has no line authority and is not in the chain of command."),
    v("u03x3", "centralization", "Keeping important decisions at the Head Office, the centre of the organization."),
    v("u03x4", "matrix management", "A structure in which people report to more than one superior."),
    v("u03x5", "functional organization", "Dividing a business into departments such as production, finance, marketing and personnel."),
    v("u03x6", "accountability", "Being required to explain your decisions to the person above you."),
    v("u03x7", "flat hierarchy", "An organization with only a few levels of management."),
    v("u03x8", "tall hierarchy", "An organization with many levels of management."),
    v("u03x9", "autonomous team", "A temporary group responsible for a whole project, which is split up when the project is finished."),
  ],
  u04: [
    v("u04x1", "power distance", "How people in a society cope with inequality and relate to more powerful individuals."),
    v("u04x2", "high-power distance", "A culture in which subordinates expect formal hierarchies and accept authoritarian relationships."),
    v("u04x3", "low-power distance", "A culture in which subordinates see themselves as equals of their supervisors."),
    v("u04x4", "linear-active", "In the Lewis Model, people who plan, organize and do one thing at a time."),
    v("u04x5", "multi-active", "In the Lewis Model, people who are lively, do many things at once and are people-oriented."),
    v("u04x6", "reactive", "In the Lewis Model, people who listen and react carefully to the other person's position."),
    v("u04x7", "collectivist", "A culture that values the group more than the individual."),
    v("u04x8", "lose face", "To be publicly humiliated or to lose other people's respect."),
    v("u04x9", "intuition", "Understanding something immediately, without conscious reasoning."),
    v("u04x10", "compromise", "An agreement in which each side gives up part of what it wanted."),
    v("u04x11", "eye contact", "Looking directly at another person's eyes while speaking or listening."),
    v("u04x12", "status", "The amount of respect and importance a person has in a group."),
    v("u04x13", "connections", "People you know who can help you, especially in business."),
    v("u04x14", "improvise", "To do something without preparation, using whatever is available."),
  ],
  u05: [
    v("u05x1", "vacancy", "A job that is available because nobody is doing it at the moment."),
    v("u05x2", "applicant", "A person who asks to be considered for a job."),
    v("u05x3", "curriculum vitae | CV", "A written record of your education and the jobs you have done, used when applying for a job."),
    v("u05x4", "covering letter", "A letter sent with a CV to say why you want the job."),
    v("u05x5", "short-list", "A small group of candidates chosen from all the applicants and invited to an interview."),
    v("u05x6", "psychometric test", "A test that looks at the psychological traits of an applicant."),
    v("u05x7", "headhunter", "A person or firm that finds senior managers for a company, often people who already have a job."),
    v("u05x8", "probationary period", "A time at the start of a job when the employer checks that the new person is suitable."),
    v("u05x9", "reference", "A statement about a person's character and ability, written by someone who knows them."),
    v("u05x10", "equal opportunities", "Employing people regardless of their sex, skin colour, religion or disability."),
  ],
  u06: [
    v("u06x1", "quaternary sector", "The part of the economy that provides information services such as computing, ICT, consultancy and research."),
    v("u06x2", "franchise", "A business in which someone pays to use another company's name and way of working."),
    v("u06x3", "joint venture", "A business activity started by two or more companies working together."),
    v("u06x4", "prospectus", "A document a public company publishes when it offers shares for sale."),
    v("u06x5", "corporation", "The usual American word for a limited company."),
    v("u06x6", "bankruptcy", "The legal state of a person or company that cannot pay its debts."),
  ],
  u07: [
    v("u07x1", "Kaizen", "A Japanese word for continuous improvement, focused on eliminating waste through the ideas of the workers."),
    v("u07x2", "overproduction", "Making goods before customers have ordered them, which raises storage costs."),
    v("u07x3", "lead time", "The time between placing an order and receiving the goods."),
    v("u07x4", "optimum capacity", "The most efficient level of production, so that costs are kept to a minimum."),
    v("u07x5", "assembly line", "A production system in which a product moves through a factory as new parts are added."),
    v("u07x6", "finished goods", "Complete products that are ready to sell."),
    v("u07x7", "product recall", "The removal from sale of an item that might be dangerous to the people who bought it."),
    v("u07x8", "offshore manufacturing", "Making goods in another country so that they can be imported to the domestic market."),
    v("u07x9", "planned obsolescence", "Designing products so that they have a limited life and must be replaced sooner."),
    v("u07x10", "supply chain", "The manufacturers, wholesalers and distributors who make, deliver and sell a product."),
    v("u07x11", "zero defects", "A standard that allows no faults in the goods leaving the factory."),
    v("u07x12", "raw materials", "Basic items, such as wood or iron ore, that must be treated before they can be used."),
    v("u07x13", "random sampling", "Testing a few items from a batch to judge the quality of the whole batch."),
  ],
  u08: [
    v("u08x1", "supply chain", "The network that buys materials, turns them into finished products, and delivers those products to customers."),
    v("u08x2", "push strategy", "Producing and sending goods based on a forecast, even before customers order them."),
    v("u08x3", "pull strategy", "Producing goods only when there is actual customer demand, which keeps inventory low."),
    v("u08x4", "cargo", "Goods carried by a ship, aircraft or other vehicle."),
    v("u08x5", "freight", "Goods being transported, and the system of moving them."),
    v("u08x6", "warehousing", "Storing goods in a building until they are needed."),
    v("u08x7", "procurement", "Buying the materials and services a company needs."),
    v("u08x8", "customs clearance", "The act of passing goods through customs so they can enter or leave a country."),
    v("u08x9", "logistician", "A specialist in logistics."),
    v("u08x10", "provider", "A person or company whose business is to supply a particular service or commodity."),
    v("u08x11", "forecasting", "Estimating how many goods will be needed in the future."),
    v("u08x12", "inventory", "The stock of materials, unfinished work and finished goods a business holds."),
    v("u08x13", "distribution", "Moving finished goods from the producer to the customer."),
    v("u08x14", "freight forwarder", "A person who arranges the transport of goods by sea, air, road or rail."),
    v("u08x15", "bottleneck", "A point in a process where work slows down because too much is trying to pass through."),
  ],
  u09: [
    v("u09x1", "benchmarking", "Measuring your performance against companies that are best in class, then using that information to improve."),
    v("u09x2", "tolerance", "The amount by which a measurement can vary before the piece becomes a defect."),
    v("u09x3", "ISO 9000", "A set of international standards of quality. A company can be audited and then say it is certified."),
    v("u09x4", "nonconformance", "A situation in which a requirement has not been met. It need not be a serious defect."),
    v("u09x5", "Six Sigma", "A quality method that uses a very disciplined approach to eliminate defects in manufacturing."),
    v("u09x6", "key performance indicator | KPI", "A statistical measure of how well an organization is doing in a particular area."),
    v("u09x7", "leading indicator", "A measure that predicts a future result, such as staff satisfaction predicting quality."),
    v("u09x8", "lagging indicator", "A measure that shows a result after the event, such as the number of warranty claims."),
    v("u09x9", "zero defects", "The aim that no faulty items are produced, so work is right the first time."),
    v("u09x10", "quality circle", "A small voluntary group of workers who meet to discuss quality problems and suggest solutions."),
    v("u09x11", "warranty", "A promise to repair or replace a product if it fails within a stated time."),
    v("u09x12", "defect", "A fault in a product."),
    v("u09x13", "customer expectations", "What the buyer believes a product or service should be like."),
    v("u09x14", "reliability", "The quality of working well for a long time without breaking."),
    v("u09x15", "durability", "The quality of lasting a long time."),
    v("u09x16", "prevention", "Stopping defects before they happen, which quality theorists say is cheaper than repairing them."),
  ],
  u10: [
    v("u10x1", "early adopter", "A customer who buys a new product soon after it is launched, often at a high price."),
    v("u10x2", "skimming", "Setting a high price at first and then gradually lowering it."),
    v("u10x3", "saturation", "The point at which a market cannot grow any further because almost everyone who wants the product already has it."),
    v("u10x4", "brand", "A name, design or symbol that identifies a product and distinguishes it from rivals."),
    v("u10x5", "niche", "A small, specialized part of a market."),
    v("u10x6", "introduction", "The first stage of the product life cycle, when sales are low and the product may still be making a loss."),
    v("u10x7", "maturity", "The stage of the product life cycle when sales growth slows and then stabilizes."),
    v("u10x8", "decline", "The stage of the product life cycle when sales fall and many products are withdrawn."),
  ],
  u11: [
    v("u11x1", "endorse", "When a celebrity says in an advertisement how good a product is."),
    v("u11x2", "hoarding", "The British word for a large outdoor advertising sign, also called a billboard."),
    v("u11x3", "sample", "A small amount of a new product given free so that customers can try it."),
    v("u11x4", "point-of-sale", "Advertising done at the place where the product is sold."),
    v("u11x5", "sponsorship", "Paying to be associated with a sports or arts event as a way of advertising."),
    v("u11x6", "word-of-mouth", "Advertising that happens when a satisfied customer recommends a product to friends."),
    v("u11x7", "commercial", "An advertisement on television or radio."),
    v("u11x8", "slogan", "A short phrase used in advertising so that people remember the product."),
    v("u11x9", "target market", "The group of customers whose needs a company plans to satisfy and therefore to advertise to."),
    v("u11x10", "media plan", "The choice of how and where to advertise, and in what proportions."),
    v("u11x11", "brief", "A statement of the objectives of an advertising campaign, given to the agency."),
    v("u11x12", "publicity", "Favourable mentions of a company or product that the company does not pay for."),
  ],
  u12: [
    v("u12x1", "legal tender", "Money that must by law be accepted in payment."),
    v("u12x2", "refund", "Money returned to a customer who brings a faulty product back to the shop."),
    v("u12x3", "receipt", "A piece of paper showing that you have paid for something."),
    v("u12x4", "instalment", "One of a series of regular payments for something expensive, such as a car."),
    v("u12x5", "standing order", "An instruction to a bank to pay a fixed sum to someone at regular intervals."),
    v("u12x6", "direct debit", "Permission for a company to take varying amounts from your account to pay bills."),
    v("u12x7", "spread", "The difference between the interest a bank pays on deposits and the interest it charges on loans."),
    v("u12x8", "interest", "The price paid for borrowing money, or the money a bank pays you for keeping a deposit."),
    v("u12x9", "wage", "Money paid to a worker, traditionally in cash each week."),
  ],
  u13: [
    v("u13x1", "income", "All the money received from business activities during a given period."),
    v("u13x2", "expenditure", "All the money a business spends on goods or services during a given period."),
    v("u13x3", "budget", "A financial plan showing expected income and expenditure."),
    v("u13x4", "asset", "Anything owned by a business, such as cash, buildings or machines."),
    v("u13x5", "liability", "Money a company will have to pay to someone else in the future, including debts, taxes and interest."),
    v("u13x6", "debit", "An entry in an account that records a payment made."),
    v("u13x7", "credit", "An entry in an account that records a payment received."),
    v("u13x8", "intangible", "Having no physical existence, so that you cannot touch it."),
    v("u13x9", "accrued", "Describing a cost that has been incurred but not yet invoiced."),
    v("u13x10", "forensic accounting", "Examining financial records because illegal activity is suspected."),
  ],
  u14: [
    v("u14x1", "policy-maker", "A person in government or a central bank who decides economic policy."),
    v("u14x2", "interest rate", "The price of borrowing money. Cutting it is a fast way to support a weak economy."),
    v("u14x3", "tax cut", "A reduction in tax, which leaves people with more money to spend."),
    v("u14x4", "labour market", "The supply of people available for work, and the jobs available to them."),
    v("u14x5", "inflation", "A general rise in prices. Growth caused by very low interest rates may lead to it."),
  ],
  u15: [
    v("u15x1", "above board", "Completely open and honest, with nothing hidden."),
    v("u15x2", "integrity", "The quality of being honest and having strong moral principles."),
    v("u15x3", "probity", "Complete honesty, especially in business or professional life."),
    v("u15x4", "misconduct", "Unacceptable or illegal behaviour in a job."),
    v("u15x5", "transparency", "Being open about what you do, so that outsiders can understand it."),
    v("u15x6", "accountability", "Being required to explain your actions and ready to accept responsibility for them."),
    v("u15x7", "stakeholder", "Any person or group affected by a company's actions, such as employees, customers or the local community."),
    v("u15x8", "code of ethics", "A written set of rules saying how a company's people should behave."),
    v("u15x9", "whistle-blower", "A person who reports illegal or unethical behaviour inside an organization."),
    v("u15x10", "bribery", "Giving money or gifts to persuade someone to do something dishonest."),
    v("u15x11", "volunteerism", "The CSR dimension in which employees give their time to help the community."),
    v("u15x12", "sustainability", "Meeting present needs without damaging the ability of future generations to meet theirs."),
  ],
  u16: [
    v("u16x1", "delayering", "Removing levels of middle management to make an organization flatter and more flexible."),
    v("u16x2", "job sharing", "Two or more people working part-time to do a job that one person would normally do full-time."),
    v("u16x3", "flexible labour market", "A situation in which it is easy for companies to hire staff who are not permanent."),
    v("u16x4", "casual work", "Temporary employment that is not regular or fixed."),
    v("u16x5", "contract work", "Temporary employment to do a specific project or piece of work."),
    v("u16x6", "rightsizing", "Another word for downsizing, though it can also mean making an organization larger."),
    v("u16x7", "redundancy", "Losing a job because the company no longer needs that work to be done."),
    v("u16x8", "outsourcing", "Using another business to supply components or services instead of doing the work inside the company."),
    v("u16x9", "relocation", "Moving some of a company's activities to another place or country."),
    v("u16x10", "core workforce", "The central, permanent employees of a company, as opposed to temporary staff."),
    v("u16x11", "make redundant", "To dismiss a worker because their job is no longer needed."),
  ],
  u17: [
    v("u17x1", "EXW | ex works", "An Incoterm: the seller makes the goods available at their own premises, and the buyer pays for everything after that."),
    v("u17x2", "FOB | free on board", "An Incoterm: the seller pays for transport to the ship and for loading onto it."),
    v("u17x3", "CIF | cost, insurance and freight", "An Incoterm: the seller pays the sea freight and the insurance, but responsibility ends at the destination port."),
    v("u17x4", "DDP | delivered duty paid", "An Incoterm: the seller pays for everything, including customs clearance, until the goods reach the buyer."),
    v("u17x5", "customs duty", "A tax charged on goods when they enter a country."),
    v("u17x6", "FAS | free alongside ship", "An Incoterm: the seller pays to bring the goods to the dock, and the buyer pays for loading onto the ship."),
    v("u17x7", "embargo", "An official ban on trade with a particular country or in particular goods."),
    v("u17x8", "dumping", "Selling exports at a price below the cost of production in order to win a foreign market."),
    v("u17x9", "subsidy", "Money a government pays to local producers so that they can compete with imports."),
    v("u17x10", "documentation", "The paperwork needed to export goods, such as invoices and certificates."),
  ],
};
